export type IconName =
  | 'logo'
  | 'logo-footer'
  | 'search'
  | 'earth-lang'
  | 'facebook'
  | 'instagram'
  | 'linkedin'
  | 'telegram'
  | 'twitter'
  | 'favorite-star'
  | 'favorite-star-filled'
  | 'loader'
  | 'no-data'
  | 'faq-arrow';
